/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProspectRouteImport } from './routes/prospect'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectRoute = ProspectRouteImport.update({
  id: '/prospect',
  path: '/prospect',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/campaigns': typeof CampaignsRoute
  '/dashboard': typeof DashboardRoute
  '/leads': typeof LeadsRoute
  '/messages': typeof MessagesRoute
  '/prospect': typeof ProspectRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/templates': typeof TemplatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/campaigns': typeof CampaignsRoute
  '/dashboard': typeof DashboardRoute
  '/leads': typeof LeadsRoute
  '/messages': typeof MessagesRoute
  '/prospect': typeof ProspectRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/templates': typeof TemplatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/campaigns': typeof CampaignsRoute
  '/dashboard': typeof DashboardRoute
  '/leads': typeof LeadsRoute
  '/messages': typeof MessagesRoute
  '/prospect': typeof ProspectRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/templates': typeof TemplatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/campaigns'
    | '/dashboard'
    | '/leads'
    | '/messages'
    | '/prospect'
    | '/settings'
    | '/signin'
    | '/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/campaigns'
    | '/dashboard'
    | '/leads'
    | '/messages'
    | '/prospect'
    | '/settings'
    | '/signin'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/campaigns'
    | '/dashboard'
    | '/leads'
    | '/messages'
    | '/prospect'
    | '/settings'
    | '/signin'
    | '/templates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  CampaignsRoute: typeof CampaignsRoute
  DashboardRoute: typeof DashboardRoute
  LeadsRoute: typeof LeadsRoute
  MessagesRoute: typeof MessagesRoute
  ProspectRoute: typeof ProspectRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  TemplatesRoute: typeof TemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospect': {
      id: '/prospect'
      path: '/prospect'
      fullPath: '/prospect'
      preLoaderRoute: typeof ProspectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  CampaignsRoute: CampaignsRoute,
  DashboardRoute: DashboardRoute,
  LeadsRoute: LeadsRoute,
  MessagesRoute: MessagesRoute,
  ProspectRoute: ProspectRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  TemplatesRoute: TemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
